#rating wc

#specific list of stopwords
stop_words = unlist(strsplit("nan,a,able,about,product,across,after,all,almost,also,am,among,an,and,any,are,as,at,be,because,been,but,by,can,cannot,could,dear,did,do,does,either,else,ever,every,for,from,get,got,had,has,have,he,her,hers,him,his,how,however,i,if,in,into,is,it,its,just,least,let,like,likely,may,me,might,most,must,my,neither,no,nor,not,of,off,often,on,only,or,other,our,own,rather,said,say,says,she,should,since,so,some,than,that,the,their,them,then,there,these,they,this,tis,to,too,twas,us,wants,was,we,were,what,when,where,which,while,who,whom,why,will,with,would,yet,you,your,id,item,it\'s,don\'t",","))
#main seller data frame
ebay_df= read.csv("ebay-prediction.csv",stringsAsFactors = FALSE)
Encoding(ebay_df$seller_code)="latin1"
Encoding(ebay_df$seller_name)="latin1"
Encoding(ebay_df$seller_store)="latin1"
Encoding(ebay_df$pos_feedback)="latin1"
Encoding(ebay_df$neg_feedback)="latin1"
iconv(ebay_df$seller_code, "latin1", "ASCII", sub="")
iconv(ebay_df$seller_name, "latin1", "ASCII", sub="")
iconv(ebay_df$seller_store, "latin1", "ASCII", sub="")
iconv(ebay_df$pos_feedback, "latin1", "ASCII", sub="")
iconv(ebay_df$neg_feedback, "latin1", "ASCII", sub="")
#1 Rated
oneRated= filter(ebay_df,ebay_df$predicted_rating >=-1 & ebay_df$predicted_rating<2)
oneRatedReview=trimws(oneRated$neg_feedback)
oneRated_docs=Corpus(VectorSource(oneRatedReview))
#2 Rated
twoRated= filter(ebay_df,ebay_df$predicted_rating >=2 & ebay_df$predicted_rating<3)
twoRatedReview=trimws(twoRated$neg_feedback)
twoRated_docs=Corpus(VectorSource(twoRatedReview))
#3 Rated
threeRated= filter(ebay_df,ebay_df$predicted_rating >=3 & ebay_df$predicted_rating<4)
threeRatedReview=trimws(threeRated$neg_feedback)
threeRated_docs=Corpus(VectorSource(threeRatedReview))
#4 Rated
fourRated= filter(ebay_df,ebay_df$predicted_rating >=4 & ebay_df$predicted_rating<5)
fourRatedReview=trimws(fourRated$neg_feedback)
fourRated_docs=Corpus(VectorSource(fourRatedReview))
#5 Rated
fiveRated= filter(ebay_df,ebay_df$predicted_rating >=5)
fiveRatedReview=trimws(fiveRated$neg_feedback)
fiveRated_docs=Corpus(VectorSource(fiveRatedReview))

#Positive feedback
#1 Rated 
oneRatedReview_pos=trimws(oneRated$pos_feedback)
oneRated_docs_pos=Corpus(VectorSource(oneRatedReview_pos))
#2 Rated
twoRatedReview_pos=trimws(twoRated$pos_feedback)
twoRated_docs_pos=Corpus(VectorSource(twoRatedReview_pos))
#3 Rated
threeRatedReview_pos=trimws(threeRated$pos_feedback)
threeRated_docs_pos=Corpus(VectorSource(threeRatedReview_pos))
#4 Rated
fourRatedReview_pos=trimws(fourRated$pos_feedback)
fourRated_docs_pos=Corpus(VectorSource(fourRatedReview_pos))
#5 Rated
fiveRatedReview_pos=trimws(fiveRated$pos_feedback)
fiveRated_docs_pos=Corpus(VectorSource(fiveRatedReview_pos))

#space
toSpace= content_transformer(function(x,pattern)gsub(pattern," ",x))
#inspect(docs)
oneRated_docs=tm_map(oneRated_docs,toSpace,"/")
oneRated_docs=tm_map(oneRated_docs,toSpace,"@")
oneRated_docs=tm_map(oneRated_docs,toSpace,"\\|")
oneRated_docs=tm_map(oneRated_docs,content_transformer(tolower))
oneRated_docs=tm_map(oneRated_docs,removeNumbers)
oneRated_docs=tm_map(oneRated_docs,removeWords,stopwords("english"))
oneRated_docs=tm_map(oneRated_docs,removeWords,c(stop_words))
oneRated_docs=tm_map(oneRated_docs,removePunctuation)
oneRated_docs=tm_map(oneRated_docs,stripWhitespace)

oneRated_docs_pos=tm_map(oneRated_docs_pos,toSpace,"/")
oneRated_docs_pos=tm_map(oneRated_docs_pos,toSpace,"@")
oneRated_docs_pos=tm_map(oneRated_docs_pos,toSpace,"\\|")
oneRated_docs_pos=tm_map(oneRated_docs_pos,content_transformer(tolower))
oneRated_docs_pos=tm_map(oneRated_docs_pos,removeNumbers)
oneRated_docs_pos=tm_map(oneRated_docs_pos,removeWords,stopwords("english"))
oneRated_docs_pos=tm_map(oneRated_docs_pos,removeWords,c(stop_words))
oneRated_docs_pos=tm_map(oneRated_docs_pos,removePunctuation)
oneRated_docs_pos=tm_map(oneRated_docs_pos,stripWhitespace)

twoRated_docs=tm_map(twoRated_docs,toSpace,"/")
twoRated_docs=tm_map(twoRated_docs,toSpace,"@")
twoRated_docs=tm_map(twoRated_docs,toSpace,"\\|")
twoRated_docs=tm_map(twoRated_docs,content_transformer(tolower))
twoRated_docs=tm_map(twoRated_docs,removeNumbers)
twoRated_docs=tm_map(twoRated_docs,removeWords,stopwords("english"))
twoRated_docs=tm_map(twoRated_docs,removeWords,c(stop_words))
twoRated_docs=tm_map(twoRated_docs,removePunctuation)
twoRated_docs=tm_map(twoRated_docs,stripWhitespace)

twoRated_docs_pos=tm_map(twoRated_docs_pos,toSpace,"/")
twoRated_docs_pos=tm_map(twoRated_docs_pos,toSpace,"@")
twoRated_docs_pos=tm_map(twoRated_docs_pos,toSpace,"\\|")
twoRated_docs_pos=tm_map(twoRated_docs_pos,content_transformer(tolower))
twoRated_docs_pos=tm_map(twoRated_docs_pos,removeNumbers)
twoRated_docs_pos=tm_map(twoRated_docs_pos,removeWords,stopwords("english"))
twoRated_docs_pos=tm_map(twoRated_docs_pos,removeWords,c(stop_words))
twoRated_docs_pos=tm_map(twoRated_docs_pos,removePunctuation)
twoRated_docs_pos=tm_map(twoRated_docs_pos,stripWhitespace)

threeRated_docs=tm_map(threeRated_docs,toSpace,"/")
threeRated_docs=tm_map(threeRated_docs,toSpace,"@")
threeRated_docs=tm_map(threeRated_docs,toSpace,"\\|")
threeRated_docs=tm_map(threeRated_docs,content_transformer(tolower))
threeRated_docs=tm_map(threeRated_docs,removeNumbers)
threeRated_docs=tm_map(threeRated_docs,removeWords,stopwords("english"))
threeRated_docs=tm_map(threeRated_docs,removeWords,c(stop_words))
threeRated_docs=tm_map(threeRated_docs,removePunctuation)
threeRated_docs=tm_map(threeRated_docs,stripWhitespace)

threeRated_docs_pos=tm_map(threeRated_docs_pos,toSpace,"/")
threeRated_docs_pos=tm_map(threeRated_docs_pos,toSpace,"@")
threeRated_docs_pos=tm_map(threeRated_docs_pos,toSpace,"\\|")
threeRated_docs_pos=tm_map(threeRated_docs_pos,content_transformer(tolower))
threeRated_docs_pos=tm_map(threeRated_docs_pos,removeNumbers)
threeRated_docs_pos=tm_map(threeRated_docs_pos,removeWords,stopwords("english"))
threeRated_docs_pos=tm_map(threeRated_docs_pos,removeWords,c(stop_words))
threeRated_docs_pos=tm_map(threeRated_docs_pos,removePunctuation)
threeRated_docs_pos=tm_map(threeRated_docs_pos,stripWhitespace)

fourRated_docs=tm_map(fourRated_docs,toSpace,"/")
fourRated_docs=tm_map(fourRated_docs,toSpace,"@")
fourRated_docs=tm_map(fourRated_docs,toSpace,"\\|")
fourRated_docs=tm_map(fourRated_docs,content_transformer(tolower))
fourRated_docs=tm_map(fourRated_docs,removeNumbers)
fourRated_docs=tm_map(fourRated_docs,removeWords,stopwords("english"))
fourRated_docs=tm_map(fourRated_docs,removeWords,c(stop_words))
fourRated_docs=tm_map(fourRated_docs,removePunctuation)
fourRated_docs=tm_map(fourRated_docs,stripWhitespace)

fourRated_docs_pos=tm_map(fourRated_docs_pos,toSpace,"/")
fourRated_docs_pos=tm_map(fourRated_docs_pos,toSpace,"@")
fourRated_docs_pos=tm_map(fourRated_docs_pos,toSpace,"\\|")
fourRated_docs_pos=tm_map(fourRated_docs_pos,content_transformer(tolower))
fourRated_docs_pos=tm_map(fourRated_docs_pos,removeNumbers)
fourRated_docs_pos=tm_map(fourRated_docs_pos,removeWords,stopwords("english"))
fourRated_docs_pos=tm_map(fourRated_docs_pos,removeWords,c(stop_words))
fourRated_docs_pos=tm_map(fourRated_docs_pos,removePunctuation)
fourRated_docs_pos=tm_map(fourRated_docs_pos,stripWhitespace)

fiveRated_docs=tm_map(fiveRated_docs,toSpace,"/")
fiveRated_docs=tm_map(fiveRated_docs,toSpace,"@")
fiveRated_docs=tm_map(fiveRated_docs,toSpace,"\\|")
fiveRated_docs=tm_map(fiveRated_docs,content_transformer(tolower))
fiveRated_docs=tm_map(fiveRated_docs,removeNumbers)
fiveRated_docs=tm_map(fiveRated_docs,removeWords,stopwords("english"))
fiveRated_docs=tm_map(fiveRated_docs,removeWords,c(stop_words))
fiveRated_docs=tm_map(fiveRated_docs,removePunctuation)
fiveRated_docs=tm_map(fiveRated_docs,stripWhitespace)

fiveRated_docs_pos=tm_map(fiveRated_docs_pos,toSpace,"/")
fiveRated_docs_pos=tm_map(fiveRated_docs_pos,toSpace,"@")
fiveRated_docs_pos=tm_map(fiveRated_docs_pos,toSpace,"\\|")
fiveRated_docs_pos=tm_map(fiveRated_docs_pos,content_transformer(tolower))
fiveRated_docs_pos=tm_map(fiveRated_docs_pos,removeNumbers)
fiveRated_docs_pos=tm_map(fiveRated_docs_pos,removeWords,stopwords("english"))
fiveRated_docs_pos=tm_map(fiveRated_docs_pos,removeWords,c(stop_words))
fiveRated_docs_pos=tm_map(fiveRated_docs_pos,removePunctuation)
fiveRated_docs_pos=tm_map(fiveRated_docs_pos,stripWhitespace)
#Dcoument term matrix making
oneRated_dtrm=TermDocumentMatrix(oneRated_docs)
twoRated_dtrm=TermDocumentMatrix(twoRated_docs)
threeRated_dtrm=TermDocumentMatrix(threeRated_docs)
fourRated_dtrm=TermDocumentMatrix(fourRated_docs)
fiveRated_dtrm=TermDocumentMatrix(fiveRated_docs)
oneRated_dtrm_pos=TermDocumentMatrix(oneRated_docs_pos)
twoRated_dtrm_pos=TermDocumentMatrix(twoRated_docs_pos)
threeRated_dtrm_pos=TermDocumentMatrix(threeRated_docs_pos)
fourRated_dtrm_pos=TermDocumentMatrix(fourRated_docs_pos)
fiveRated_dtrm_pos=TermDocumentMatrix(fiveRated_docs_pos)

oneRated_dmatrix= as.matrix(oneRated_dtrm)
twoRated_dmatrix= as.matrix(twoRated_dtrm)
threeRated_dmatrix= as.matrix(threeRated_dtrm)
fourRated_dmatrix= as.matrix(fourRated_dtrm)
fiveRated_dmatrix= as.matrix(fiveRated_dtrm)
oneRated_dmatrix_pos= as.matrix(oneRated_dtrm_pos)
twoRated_dmatrix_pos= as.matrix(twoRated_dtrm_pos)
threeRated_dmatrix_pos= as.matrix(threeRated_dtrm_pos)
fourRated_dmatrix_pos= as.matrix(fourRated_dtrm_pos)
fiveRated_dmatrix_pos= as.matrix(fiveRated_dtrm_pos)
#frequence vector
oneRated_dvec=sort(rowSums(oneRated_dmatrix),decreasing = TRUE)
twoRated_dvec=sort(rowSums(twoRated_dmatrix),decreasing = TRUE)
threeRated_dvec=sort(rowSums(threeRated_dmatrix),decreasing = TRUE)
fourRated_dvec=sort(rowSums(fourRated_dmatrix),decreasing = TRUE)
fiveRated_dvec=sort(rowSums(fiveRated_dmatrix),decreasing = TRUE)

oneRated_dvec_pos=sort(rowSums(oneRated_dmatrix_pos),decreasing = TRUE)
twoRated_dvec_pos=sort(rowSums(twoRated_dmatrix_pos),decreasing = TRUE)
threeRated_dvec_pos=sort(rowSums(threeRated_dmatrix_pos),decreasing = TRUE)
fourRated_dvec_pos=sort(rowSums(fourRated_dmatrix_pos),decreasing = TRUE)
fiveRated_dvec_pos=sort(rowSums(fiveRated_dmatrix_pos),decreasing = TRUE)
#data frames
oneRated_dframe=data.frame(word=names(oneRated_dvec),freq=oneRated_dvec)
twoRated_dframe=data.frame(word=names(twoRated_dvec),freq=twoRated_dvec)
threeRated_dframe=data.frame(word=names(threeRated_dvec),freq=threeRated_dvec)
fourRated_dframe=data.frame(word=names(fourRated_dvec),freq=fourRated_dvec)
fiveRated_dframe=data.frame(word=names(fiveRated_dvec),freq=fiveRated_dvec)

oneRated_dframe_pos=data.frame(word=names(oneRated_dvec_pos),freq=oneRated_dvec_pos)
twoRated_dframe_pos=data.frame(word=names(twoRated_dvec_pos),freq=twoRated_dvec_pos)
threeRated_dframe_pos=data.frame(word=names(threeRated_dvec_pos),freq=threeRated_dvec_pos)
fourRated_dframe_pos=data.frame(word=names(fourRated_dvec_pos),freq=fourRated_dvec_pos)
fiveRated_dframe_pos=data.frame(word=names(fiveRated_dvec_pos),freq=fiveRated_dvec_pos)
#setting head params
head(oneRated_dframe,10)
head(twoRated_dframe,10)
head(threeRated_dframe,10)
head(fourRated_dframe,10)
head(fiveRated_dframe,10)

head(oneRated_dframe_pos,10)
head(twoRated_dframe_pos,10)
head(threeRated_dframe_pos,10)
head(fourRated_dframe_pos,10)
head(fiveRated_dframe_pos,10)

set.seed(1235)
